### ISSUE TITLE
Support imports of namespaces in python>=3.3 (modules without __init__.py files)

### ISSUE THREAD

**Issue by mishas** [PyCQA/pylint#842]
Python 3.3 introduced "[Implicit Namespace Packages](https://docs.python.org/3.3/whatsnew/3.3.html#pep-420-implicit-namespace-packages)" (based on [PEP-420](https://www.python.org/dev/peps/pep-0420/)), which states the following:
"Native support for package directories that don’t require `__init__.py` marker files [...]".

In other words, if I have the following file structure (without any `__init__.py` files whatsoever):
```
foo/
    bar/
        baz.py
blah.py
```
And the content of blah.py is `from foo.bar import baz; print(baz)`, then `python3.5 ./blah.py` will successfully output: `<module 'foo.bar.baz' from '/tmp/foo/bar/baz.py'>`.

The problem is, that `pylint ./blah.py` outputs:
`E:  1, 0: Unable to import 'foo.bar' (import-error)`

I tried to manipulate `sys.path` (from `init-hook` of my `.pylintrc`) in any which way, and nothing seemed to help except for adding the `__init__.py` files everywhere :(.

**Comment by PCManticore** [comment]
Agree that this would be nice to have, but not sure when this will happen.

**Comment by srikanth-viswanathan** [comment]
This would be great to have. Is this just a minor enhancement? Out of curiosity, where would the change have to be made?

**Comment by kstrauser** [comment]
For my organization, it's not minor but a real showstopper. We use lots of namespace packages and are moving to the new implicit namespace package layout, so we can't use pylint in the mean time. Is this something a motivated would-be contributor with no prior pylint experience could reasonably fix?

**Comment by moylop260** [comment]
@kstrauser 
I had a similar issue with `import` check but I can use pylint with `pylint... --disable=import-error`
FYI You can try it to use pylint with other checks that works but disabling the checks that don't work for you

**Comment by kstrauser** [comment]
@moylop260 But I _use_ import errors. :-/ I've temporarily switched to flake8 but I'd much prefer pylint on  the CI server.

**Comment by moylop260** [comment]
Flake8 don't have `import-error` is the same if you use pylint disabling it
But is a good choice too!

**Comment by moylop260** [comment]
A big problem with use `import-error` in the CI is that many times you need a speed-up result of lint checks, but for this check (and just this check) you will need install all depends, then could be more slow the result of this build.

**Comment by PCManticore** [comment]
@kstrauser, this would probably be a bit difficult, since it will require modifications through astroid as well (the inference engine of Pylint). But if you want to tackle it, I can help you with the details.

**Comment by kstrauser** [comment]
@PCManticore Thanks, after looking at it that might be outside my current resource availability. I'm going to keep that in mind as a possibility, though.

**Comment by PCManticore** [comment]
Let's fix this before the next release. I'm assigning to me for now, but if anyone wants to chime in and help, I wouldn't mind.

**Comment by PCManticore** [comment]
For the record, I started implementing this feature. It's pretty much work in progress, but you can check these two branches https://github.com/PyCQA/pylint/commits/namespace_package and https://github.com/PyCQA/astroid/commits/namespace_package. It doesn't support Python 3.3 though, I found it a bit cumbersome to support it, but if someone needs it, say it now.

**Comment by PCManticore** [comment]
This should be fixed, you'll need the pylint's and astroid's master branch if you want to test. Please give it a go and let me know if you have problems with it.

**Comment by moylop260** [comment]
@PCManticore 
FYI the [build is red](https://travis-ci.org/PyCQA/pylint/builds/128873232) of the change https://github.com/PyCQA/pylint/commit/38a56db2c4931feae2e6ca7141b9a143b3354114
IMHO we should avoid use `push` directly without a `pull request`

**Comment by abstrus** [comment]
This is closed but I don't think it was merged.  Any news ?

**Comment by PCManticore** [comment]
This is available in the master branch. It will be released though in a
couple of months, since we have some more work to do. You can check the
milestone page to see what's blocking us so far.

**Comment by janosh** [comment]
> This is available in the master branch. It will be released though in a couple of months, ...

I'm still having this problem? Was the release ever published?

**Comment by PCManticore** [comment]
This was already released @janosh but there might be some bugs lurking around. Please open a new issue with some reproduction examples.

**Comment by janosh** [comment]
Never mind, I was specifying the imports from the wrong starting point, i.e. `from package import module` rather than `from src.package import module`. Working now.

**Comment by webknjaz** [comment]
FTR this error pops up for me with the latest pylint under Python 3.7 but occasionally: only in Travis CI and GitHub Actions CI/CD. No errors locally. I've been trying to figure out the difference between envs but still no luck...
